project:
  type: website
  render:
    - "*.qmd"
    - "!EDA/"
    - "!prototyping/"
website:
  title: "prod-shiny-workshop"
  description: "Website for the rstudio::conf(2022) workshop on building Production-Quality Shiny Applications"
  logo: images/shinybrain.png
  favicon: images/favicon.ico
  site-url: "https://shinyprod.com/"
  repo-url: "https://github.com/rstudio-conf-2022/shiny-prod-apps"
  repo-actions: [edit, issue]
  opengraph: true
  page-navigation: true
  navbar:
    background: primary
    logo: images/Shiny.png
    #foreground: '#00264d' # primary, secondary, success, danger, warning, info, light, dark
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: schedule.qmd
        text: Schedule
      - href: resources.qmd
        text: Resources
      - href: setup.qmd
        text: Setup
  twitter-card:
    creator: "@theRcast"
    image: "/images/twitter-card.png"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    #css: styles.css
    toc: true

# https://quarto.org/docs/output-formats/html-themes.html#dark-mode

